import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, Star } from "lucide-react";
import { ProductCard } from "@/components/cards/product-card";
import { ProductBuyBox } from "@/components/shop/product-buy-box";
import { ButtonLink } from "@/components/ui/button";
import { products } from "@/lib/site-data";
import { formatCurrency } from "@/lib/utils";

export function generateStaticParams(){return products.map((product)=>({slug:product.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const product=products.find((item)=>item.slug===slug);return{title:product?.name??"Product",description:product?.description};}

export default async function ProductDetailPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=products.find((item)=>item.slug===slug);if(!product)notFound();const related=products.filter((item)=>item.slug!==slug).slice(0,4);return <><section className="bg-cream py-6"><div className="container-shell"><ButtonLink href="/shop" variant="ghost" size="sm"><ArrowLeft className="h-4 w-4"/>Back to the edit</ButtonLink></div></section><section className="bg-cream pb-20"><div className="container-shell grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative aspect-square overflow-hidden rounded-[2rem] bg-blush-100"><Image src={product.image} alt={product.name} fill priority className="object-cover" sizes="50vw"/>{product.badge?<span className="absolute left-5 top-5 rounded-full bg-ink px-4 py-2 text-[9px] font-bold uppercase tracking-wider text-white">{product.badge}</span>:null}</div><div className="lg:pl-12"><p className="eyebrow text-rose-500">{product.category}</p><h1 className="display-title mt-5 text-5xl sm:text-6xl">{product.name}</h1><div className="mt-4 flex items-center gap-3"><div className="flex gap-1">{Array.from({length:5}).map((_,index)=><Star key={index} className="h-3.5 w-3.5 fill-gold text-gold"/>)}</div><span className="text-xs text-ink/50">{product.rating} · 86 reviews</span></div><p className="mt-6 font-display text-3xl">{formatCurrency(product.price)}</p><p className="mt-5 text-sm leading-7 text-ink/60">{product.description} Designed for daily use and chosen by our artists for its beautiful feel, considered formula and dependable results.</p><div className="my-7 h-px bg-ink/10"/><ProductBuyBox slug={product.slug}/><details className="mt-8 border-t border-ink/10 py-5" open><summary className="cursor-pointer text-xs font-bold uppercase tracking-wider">How to use</summary><p className="mt-3 text-xs leading-6 text-ink/55">Use a small amount as part of your evening ritual. Massage gently into nails, cuticles and hands until absorbed.</p></details><details className="border-t border-ink/10 py-5"><summary className="cursor-pointer text-xs font-bold uppercase tracking-wider">Ingredients & care</summary><p className="mt-3 text-xs leading-6 text-ink/55">Thoughtfully formulated and suitable for most skin types. Full ingredient information is printed on your product.</p></details></div></div></section><section className="py-20"><div className="container-shell"><h2 className="display-title text-5xl">Complete the ritual</h2><div className="mt-10 grid grid-cols-2 gap-5 md:grid-cols-4">{related.map((item)=><ProductCard key={item.slug} product={item}/>)}</div></div></section></>}

